services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - es-docker-net
#    volumes:
#      - /export/hosts:/etc/nginx/certs
networks:
  es-docker-net:
    external: true
