services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - es-docker-net
    volumes:
      - easy-stack-ssl/_data/www.easyvoice.us:/etc/nginx/certs
networks:
  es-docker-net:
    external: true
