services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - es-docker-net
    volumes:
      - /var/lib/docker/volumes/easy-stack-ssl/_data:/etc/nginx/certs
networks:
  es-docker-net:
    external: true
